### ISSUE TITLE
Does not work with new exports in JSON

### ISSUE THREAD

**Issue by zmilonas** [ArmaanSethi/facebook-messages-parser-grapher#6]
So it does not work with current exports from facebook. 

From what I analyzed it seems that 

1. There is a `timestamp_ms` field for each message instead of `timestamp` field.
1. In private conversations there are two participants: yourself and the person talked to

So the bug actually shows just yourself in all graphs :)

**Comment by ArmaanSethi** [comment]
Awesome, I'll look into it soon. Maybe Facebook has changed their formatting (they seem to change it fairly often)
